AspNetCoreWindowsAuthExample/Controllers/UserInformationAdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using AspNetCoreWindowsAuthExample.Models;
using System.Threading.Tasks;
using AspNetCoreWindowsAuthExample.Services;

namespace AspNetCoreWindowsAuthExample.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class UserInformationAdminController : Controller
    {
        private readonly IUserInformationAdminService _userInformationAdminService;

        public UserInformationAdminController(IUserInformationAdminService userInformationAdminService)
        {
            _userInformationAdminService = userInformationAdminService;
        }

        // GET: UserInformationAdmin
        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? page, int? id)
        {
            var pageSize = 10;
            //Todo: make the service methods asynchronous
            var userView = _userInformationAdminService.GetIndexView(sortOrder, currentFilter, searchString, page, id, pageSize);
            return View(userView);
        }

        // GET: UserInformationAdmin/Create
        public IActionResult Create()
        {
            var createView = _userInformationAdminService.GetCreateView();
            return View(createView);
        }

        // POST: UserInformationAdmin/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserInformationId,LanId,FirstName,LastName,Email,Enabled")] UserInformation userInformation, string[] selectedUserRoles)
        {
            if (userInformation.LanId != null && _userInformationAdminService.CheckUser(userInformation.LanId))
            {
                ModelState.AddModelError("LanId", "LanId Already Exists");
            }

            if (ModelState.IsValid)
            {
                _userInformationAdminService.CreateUser(userInformation, selectedUserRoles);

                return RedirectToAction(nameof(Index));
            }
            var createView = _userInformationAdminService.GetEditView(userInformation, selectedUserRoles, "Create User");
            return View(createView);
        }

        // GET: UserInformationAdmin/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var editView = _userInformationAdminService.GetEditView((int)id, "Edit User");

            return View(editView);
        }

        // POST: UserInformationAdmin/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserInformationId,LanId,FirstName,LastName,Email,Enabled")] UserInformation userInformation, string[] selectedUserRoles)
        {
            if (id != userInformation.UserInformationId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //_context.Update(userInformation);
                    //await _context.SaveChangesAsync();
                    _userInformationAdminService.UpdateUser(userInformation, selectedUserRoles);
                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }
                return RedirectToAction(nameof(Index));
            }
            var editView = _userInformationAdminService.GetEditView(userInformation, selectedUserRoles, "Edit User");
            return View(editView);
        }

        // GET: UserInformationAdmin/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var editView = _userInformationAdminService.GetEditView((int)id, "Delete User");

            return View(editView);
        }

        // POST: UserInformationAdmin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            _userInformationAdminService.DeleteUser(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

AspNetCoreWindowsAuthExample/Views/UserInformationAdmin/Create.cshtml
@model AspNetCoreWindowsAuthExample.ViewModels.UserInfoAdminEditViewModel

@{
    ViewData["Title"] = Model.Title;
}

<br /><br />
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading"><h2>@Model.Title</h2></div>

            @if (ViewBag.Message != null)
            {
                <p class="alert-danger text-center">@ViewBag.Message</p>
            }

            <br />
            <div class="panel-body">
                <form asp-action="Create">
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="UserInformation.LanId" class="control-label"></label>
                        <input asp-for="UserInformation.LanId" class="form-control" />
                        <span asp-validation-for="UserInformation.LanId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="UserInformation.FirstName" class="control-label"></label>
                        <input asp-for="UserInformation.FirstName" class="form-control" />
                        <span asp-validation-for="UserInformation.FirstName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="UserInformation.LastName" class="control-label"></label>
                        <input asp-for="UserInformation.LastName" class="form-control" />
                        <span asp-validation-for="UserInformation.LastName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="UserInformation.Email" class="control-label"></label>
                        <input asp-for="UserInformation.Email" class="form-control" />
                        <span asp-validation-for="UserInformation.Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <div class="checkbox">
                            <label>
                                <input asp-for="UserInformation.Enabled" /> @Html.DisplayNameFor(model => model.UserInformation.Enabled)
                            </label>
                        </div>
                    </div>
                    <hr />
                    <label>Roles</label>
                    <div class="row">
                        @{
                            int cnt = 0;
                            foreach (var userRole in Model.AssignedRoleDatas)
                            {
                                if (cnt++ % 3 == 0)
                                {

                                @:</div><div class="row">

                                }

                                <div class="col-md-4">

                                    <input type="checkbox"
                                           name="selectedUserRoles"
                                           value="@userRole.UserRoleId"
                                           @(Html.Raw(userRole.Assigned ? "checked=\"checked\"" : "")) />
                                    @userRole.UserRoleId @userRole.Name
                                </div>

                            }
                        }
                    </div>
                    <hr />
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </form>
            </div>
            <div class="panel-footer">
                <a asp-action="Index">Back to List</a>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AspNetCoreWindowsAuthExample/Views/UserInformationAdmin/Delete.cshtml
@model AspNetCoreWindowsAuthExample.ViewModels.UserInfoAdminEditViewModel

@{
    ViewData["Title"] = Model.Title;
}

<br /><br />
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-danger">
            <div class="panel-heading"><h2>@Model.Title</h2></div>

            @if (Model.Message != null)
            {
                <p class="alert-danger text-center">@Model.Message</p>
            }

            <br />
            <div class="panel-body">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.UserInformation.LanId)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.UserInformation.LanId)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.UserInformation.FirstName)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.UserInformation.FirstName)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.UserInformation.LastName)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.UserInformation.LastName)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.UserInformation.Email)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.UserInformation.Email)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.UserInformation.Enabled)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.UserInformation.Enabled)
                    </dd>
                </dl>
                <hr />
                <label>Roles</label>
                <div class="row">
                    @{
                        int cnt = 0;
                        foreach (var userRole in Model.AssignedRoleDatas)
                        {
                            if (cnt++ % 3 == 0)
                            {

                            @:</div><div class="row">

                            }

                            <div class="col-md-4">

                                <input type="checkbox"
                                       name="selectedUserRoles"
                                       value="@userRole.UserRoleId"
                                       @(Html.Raw(userRole.Assigned ? "checked=\"checked\"" : "")) />
                                @userRole.UserRoleId @userRole.Name
                            </div>

                        }
                    }
                </div>
                <hr />

                <form asp-action="Delete">
                    <input type="hidden" asp-for="UserInformation.UserInformationId" />
                    <input type="submit" value="Delete" class="btn btn-danger" />
                </form>
            </div>
            <div class="panel-footer">
                <a asp-action="Index">Back to List</a>
            </div>
        </div>
    </div>
</div>

AspNetCoreWindowsAuthExample/Views/UserInformationAdmin/Edit.cshtml
@model AspNetCoreWindowsAuthExample.ViewModels.UserInfoAdminEditViewModel

@{
    ViewData["Title"] = Model.Title;
}

<br /><br />
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading"><h2>@Model.Title</h2></div>

            @if (Model.Message != null)
            {
                <p class="alert-danger text-center">@Model.Message</p>
            }

            <br />
            <div class="panel-body">
                <form asp-action="Edit">
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <input type="hidden" asp-for="UserInformation.UserInformationId" />
                    <div class="form-group">
                        <label asp-for="UserInformation.LanId" class="control-label"></label>
                        <input asp-for="UserInformation.LanId" class="form-control" />
                        <span asp-validation-for="UserInformation.LanId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="UserInformation.FirstName" class="control-label"></label>
                        <input asp-for="UserInformation.FirstName" class="form-control" />
                        <span asp-validation-for="UserInformation.FirstName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="UserInformation.LastName" class="control-label"></label>
                        <input asp-for="UserInformation.LastName" class="form-control" />
                        <span asp-validation-for="UserInformation.LastName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="UserInformation.Email" class="control-label"></label>
                        <input asp-for="UserInformation.Email" class="form-control" />
                        <span asp-validation-for="UserInformation.Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <div class="checkbox">
                            <label>
                                <input asp-for="UserInformation.Enabled" /> @Html.DisplayNameFor(model => model.UserInformation.Enabled)
                            </label>
                        </div>
                    </div>
                    <hr />
                    <label>Roles</label>
                    <div class="row">
                        @{
                            int cnt = 0;
                            foreach (var userRole in Model.AssignedRoleDatas)
                            {
                                if (cnt++ % 3 == 0)
                                {

                                @:</div><div class="row">

                                }

                                <div class="col-md-4">

                                    <input type="checkbox"
                                           name="selectedUserRoles"
                                           value="@userRole.UserRoleId"
                                           @(Html.Raw(userRole.Assigned ? "checked=\"checked\"" : "")) />
                                    @userRole.UserRoleId @userRole.Name
                                </div>

                            }
                        }
                    </div>
                    <hr />
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </form>
            </div>
            <div class="panel-footer">
                <a asp-action="Index">Back to List</a>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AspNetCoreWindowsAuthExample/Views/UserInformationAdmin/Index.cshtml
@using X.PagedList.Mvc
@using X.PagedList.Mvc.Core

@model AspNetCoreWindowsAuthExample.ViewModels.UserInfoAdminIndexViewModel

<br /><br />
<div class="col-md-10 col-md-offset-1">

    @using (Html.BeginForm("Index", "UserInformationAdmin", FormMethod.Get, new { @class = "form-inline", role = "form" }))
    {
        <p>
            @Html.TextBox("SearchString", Model.PageListAction.CurrentFilter as string, null, new { @class = "form-control", placeholder = "Find by name" })

            <input type="submit" value="Search" class="btn btn-default" />
        </p>
    }
    <div class="panel panel-default">

        <table class="table">
            <tr>
                <th>
                    LanId
                </th>
                <th>

                    @Html.ActionLink("First Name", "Index", new { sortOrder = Model.PageListAction.FirstNameSortParm, currentFilter = ViewBag.CurrentFilter })
                </th>
                <th>

                    @Html.ActionLink("Last Name", "Index", new { sortOrder = Model.PageListAction.NameSortParm, currentFilter = ViewBag.CurrentFilter })
                </th>
                <th>
                    Distributor Code
                </th>
                <th>
                    Email
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model.UserInformations)
            {
                string selectedRow = "";
                if (item.UserInformationId == ViewBag.UserInformationId)
                {
                    selectedRow = "selectedrow";
                }
                <tr class="@selectedRow">

                    <td>
                        @Html.DisplayFor(modelItem => item.LanId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LastName)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @Html.ActionLink("Select", "Index", new { id = item.UserInformationId, page = Model.UserInformations.PageNumber, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }) |
                        <a asp-area="" asp-controller="UserInformationAdmin" asp-action="Edit" asp-route-id="@item.UserInformationId">Edit</a> |
                        <a asp-area="" asp-controller="UserInformationAdmin" asp-action="Delete" asp-route-id="@item.UserInformationId">Delete</a>
                    </td>
                </tr>
            }
        </table>
    </div>
    <p>
        <a asp-area="" asp-controller="UserInformationAdmin" asp-action="Create" class="btn btn-primary">Create New User</a>
    </p>

    Page @(Model.UserInformations.PageCount < Model.UserInformations.PageNumber ? 0 : Model.UserInformations.PageNumber) of @Model.UserInformations.PageCount

    @*<pager class="pager-container" list="@Model.UserInformations" options="@PagedListRenderOptions.TwitterBootstrapPager" asp-action="Index" asp-controller="UserInformationAdmin" asp-route-keyword="@Model.UserInformations" />*@

    @Html.PagedListPager(Model.UserInformations, page => Url.Action("Index", new { id = "", page = page, sortOrder = Model.PageListAction.CurrentSort, currentFilter = Model.PageListAction.CurrentFilter }))
    <br /><br />

    @if (Model.UserRoles != null)
    {
        <div class="panel panel-default">
            <div class="panel-heading">Roles for <strong>@Model.PageListAction.LanId</strong></div>
            <table class="table">
                <tr><th>Role</th><th>Description</th></tr>

                @foreach (var item in Model.UserRoles)
                {
                    <tr><td>@item.Name</td><td>@item.Description</td></tr>
                }
            </table>
        </div>
    }
</div>
<div class="clearfix"></div>